# docker-compose.yml for Global Live Flight Scraper Agent

version: '3.9'

services:
  postgres:
    image: postgis/postgis:15-3.3  # Postgres with PostGIS
    container_name: flighttracker_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: flighttracker_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: flighttracker_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@postgres:5432/flights
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
